# Generated by Django 3.0.3 on 2020-02-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_wind', models.IntegerField()),
                ('min_temp', models.IntegerField()),
            ],
        ),
    ]
